# Generated by Django 4.2 on 2025-03-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='descripton',
            new_name='description',
        ),
    ]
