# Generated by Django 4.2 on 2025-03-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_rename_descripton_card_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
