# Generated by Django 4.2 on 2025-03-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_remove_card_description_transaction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim')], max_length=10),
        ),
    ]
